name: custom_gallery_display
description: It is like instagram gallery display and custom of camera and video
version: 0.2.2
homepage: https://github.com/AhmedAbdoElhawary/custom_gallery_display.git

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.9.7
  flutter_ringtone_player: ^3.2.0
  video_compress: ^3.1.0
  photo_manager: ^2.1.1
  shimmer: ^2.0.0
  image_crop: ^0.4.0
  octo_image: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
